[build]
command = "pnpm run build"

[site]
bucket = ".next/standalone"

[build.environment]
NODE_VERSION = "18.18.0"

[pages]
build_output_directory = ".next/static"
assets_directory = "public"

# Explicitly exclude the large webpack cache files
[pages.exclude]
patterns = ["**/.next/cache/**"]