INSERT INTO items (
    title,
    description,
    category,
    type,
    min_price,
    max_price,
    start_price,
    current_price,
    high_price,
    low_price,
    images,
    inspection_report,
    additional_info,
    auction_result
) VALUES (
    'خاتم ألماس فاخر',
    'خاتم ألماس عيار 18 قيراط مع شهادة توثيق',
    'jewelry',
    'instant',
    5000,
    15000,
    8000,
    8000,
    8000,
    8000,
    '["/images/jewelry/ring1.jpg", "/images/jewelry/ring2.jpg"]',
    '/reports/ring1.pdf',
    '{"material":"ذهب أبيض", "karat":"18", "weight_grams":"5.2"}',
    'بانتظار المزايدة'
);
